export const PREFETCH_COUNT = 300;
export const LOAD_MORE_PAGE_SIZE = 30;
export const HEAD_REFRESH_COUNT = 30;
export const THUMBNAIL_PREFETCH_PRIORITY_COUNT = 18;
export const THUMBNAIL_PREFETCH_CONCURRENCY = 8;
