require 'json'

package = JSON.parse(File.read(File.join(__dir__, 'package.json')))

Pod::Spec.new do |s|
  s.name           = 'ExpoColorLensFrameProcessor'
  s.version        = package['version']
  s.summary        = 'VisionCamera v5 Nitro ColorLensProcessor'
  s.description    = 'Nitro HybridObject for color-lens palette (RGB ArrayBuffer) and region (frame rect) MMCQ.'
  s.author         = ''
  s.homepage       = 'https://docs.expo.dev/modules/'
  s.license        = package['license']
  s.platforms      = {
    :ios => '15.1',
  }
  s.source         = { :git => '' }
  s.static_framework = true

  s.source_files = [
    # Implementation (Swift)
    'ios/**/*.{swift}',
    # Autolinking/Registration (Objective-C++)
    'ios/**/*.{m,mm}',
  ]

  s.dependency 'React-jsi'
  s.dependency 'React-callinvoker'
  s.dependency 'VisionCamera'
  s.dependency 'NitroModules'

  # Add all files generated by Nitrogen (paths relative to package root)
  load 'nitrogen/generated/ios/ExpoColorLensFrameProcessor+autolinking.rb'
  add_nitrogen_files(s)

  install_modules_dependencies(s) if defined?(install_modules_dependencies)
end
